In [4]:
url = "jdbc:postgresql://my-postgres-container:5432/postgres"
user = "postgres"
password = "postgres"

In [2]:
pyspark = SparkSession.builder.config("spark.driver.extraClassPath", "/opt/spark/jars/postgresql-42.6.0.jar") \
        .config("spark.executor.extraClassPath", "/opt/spark/jars/postgresql-42.6.0.jar") \
        .appName("Jupyter").getOrCreate()

24/12/27 21:28:32 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [5]:
events_df = spark.read.format("jdbc")\
            .option("url",url)\
            .option("driver","org.postgresql.Driver")\
            .option("dbtable","drivers_data")\
            .option("user",user)\
            .option("password",password)\
            .option("dbtable","events").load()

In [7]:
events_df.columns

['url', 'referrer', 'user_id', 'device_id', 'host', 'event_time']

In [8]:
events_df.createOrReplaceTempView('events')

In [17]:
create_user_cumulated = """
CREATE TABLE IF NOT EXISTS homework.users_cumulated (
    user_id STRING,
    -- The list of dates in the past where the user was active
    dates_active Array<DATE>,
    -- Current data for the user
    date DATE
);
"""

In [16]:
pyspark.sql('show databases').show()

+---------+
|namespace|
+---------+
| homework|
+---------+

In [18]:
pyspark.sql(create_user_cumulated)

DataFrame[]

In [23]:
user_cumulated_query = """
WITH yesterday AS (
    SELECT
        *
    FROM homework.users_cumulated
    WHERE date = to_date('2022-12-31')
),
    today AS (
            SELECT
                  CAST(user_id AS STRING),
                  CAST(event_time AS DATE) as date_active
              FROM events
              WHERE
                  CAST(event_time AS DATE) = to_date('2023-01-01')
                    AND user_id IS NOT NULL
              GROUP BY user_id, CAST(event_time AS DATE)
    )
SELECT
    COALESCE(t.user_id, y.user_id) as user_id,
    CASE WHEN y.dates_active IS NULL
            THEN array(t.date_active)
        WHEN t.date_active IS NULL
            THEN y.dates_active
        ELSE concat(array(t.date_active), y.dates_active)
        END as dates_active,
    COALESCE(t.date_active, date_add(y.date, 1)) AS date
    FROM today t
    FULL OUTER JOIN yesterday y
    ON t.user_id = y.user_id
"""

In [28]:
df = pyspark.sql(user_cumulated_query)

In [26]:
pyspark.sql('select * from events').show()

+--------------------+--------+--------------------+--------------------+--------------------+--------------------+
|                 url|referrer|             user_id|           device_id|                host|          event_time|
+--------------------+--------+--------------------+--------------------+--------------------+--------------------+
|                   /|    NULL|                NULL|99067568206611800...| www.zachwilson.tech|2023-01-09 11:55:...|
|                   /|    NULL|16647130749494100...|99067568206611800...| www.zachwilson.tech|2023-01-09 20:10:...|
|                   /|    NULL|                NULL|12048389584711700...|admin.zachwilson....|2023-01-10 04:43:...|
|                   /|    NULL|                NULL|12048389584711700...| www.zachwilson.tech|2023-01-14 05:25:...|
|                   /|    NULL|                NULL|12048389584711700...| www.zachwilson.tech|2023-01-14 05:25:...|
|                   /|    NULL|                NULL|12048389584711700...| www.zachwilson.tech|2023-01-14 05:44:...|
|          /?author=4|    NULL|                NULL|83007635388519360...| www.zachwilson.tech|2023-01-22 10:29:...|
|          /?author=5|    NULL|28540300629996805...|83007635388519360...| www.zachwilson.tech|2023-01-22 10:29:...|
|                   /|    NULL|72215507892695740...|52073353542027654...| www.zachwilson.tech|2023-01-21 23:59:...|
|         /robots.txt|    NULL|                NULL|                NULL|    www.eczachly.com|2023-01-22 00:04:...|
|            /ads.txt|    NULL|15027850815457000...|64495674649804570...|    www.eczachly.com|2023-01-22 00:04:...|
|        /app-ads.txt|    NULL|15027850815457000...|64495674649804570...|    www.eczachly.com|2023-01-22 00:05:...|
|         /robots.txt|    NULL|45566498459724703...|10598707916011500...| www.zachwilson.tech|2023-01-22 01:22:...|
|/.well-known/appl...|    NULL|15027850815457000...|64495674649804570...|    www.eczachly.com|2023-01-22 00:05:...|
|       /wp-login.php|    NULL|28540300629996805...|83007635388519360...| www.zachwilson.tech|2023-01-22 10:29:...|
|/apple-app-site-a...|    NULL|15027850815457000...|64495674649804570...|    www.eczachly.com|2023-01-22 00:05:...|
|/.well-known/node...|    NULL|15027850815457000...|64495674649804570...|    www.eczachly.com|2023-01-22 00:05:...|
|/.well-known/open...|    NULL|15027850815457000...|64495674649804570...|    www.eczachly.com|2023-01-22 00:05:...|
|/.well-known/secu...|    NULL|15027850815457000...|64495674649804570...|    www.eczachly.com|2023-01-22 00:05:...|
|          /?author=1|    NULL|28540300629996805...|83007635388519360...| www.zachwilson.tech|2023-01-22 10:29:...|
+--------------------+--------+--------------------+--------------------+--------------------+--------------------+
only showing top 20 rows

In [29]:
df

DataFrame[user_id: string, dates_active: array<date>, date: date]

In [30]:
df.show()

+--------------------+------------+----------+
|             user_id|dates_active|      date|
+--------------------+------------+----------+
|15049317011116400...|[2023-01-01]|2023-01-01|
|94468873453980500...|[2023-01-01]|2023-01-01|
|13431269135311700...|[2023-01-01]|2023-01-01|
|13527073786389900...|[2023-01-01]|2023-01-01|
|13394024080763900...|[2023-01-01]|2023-01-01|
|17375809595660200...|[2023-01-01]|2023-01-01|
|17602861391509800...|[2023-01-01]|2023-01-01|
|17996457346796300...|[2023-01-01]|2023-01-01|
|82331189944719850...|[2023-01-01]|2023-01-01|
|16899212529494500...|[2023-01-01]|2023-01-01|
|56416791558782860...|[2023-01-01]|2023-01-01|
|14156386081429200...|[2023-01-01]|2023-01-01|
|10060569187331700...|[2023-01-01]|2023-01-01|
|14839625512044600...|[2023-01-01]|2023-01-01|
|12718856434460700...|[2023-01-01]|2023-01-01|
|13547985275289400...|[2023-01-01]|2023-01-01|
|52893914368348070...|[2023-01-01]|2023-01-01|
|12615598167083900...|[2023-01-01]|2023-01-01|
|15333162782644000...|[2023-01-01]|2023-01-01|
|10945278839921100...|[2023-01-01]|2023-01-01|
+--------------------+------------+----------+
only showing top 20 rows

In [31]:
import pandas as pd

In [32]:
pd.set_option('display.max_colwidth', None)

In [33]:
df.to_pandas()

AttributeError: 'DataFrame' object has no attribute 'to_pandas'

In [36]:
df.pandas_api()

/opt/spark/python/pyspark/pandas/__init__.py:50: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(

                                    user_id  dates_active        date
0   15049317011116400000.000000000000000000  [2023-01-01]  2023-01-01
1    9446887345398050000.000000000000000000  [2023-01-01]  2023-01-01
2   13431269135311700000.000000000000000000  [2023-01-01]  2023-01-01
3   13527073786389900000.000000000000000000  [2023-01-01]  2023-01-01
4   13394024080763900000.000000000000000000  [2023-01-01]  2023-01-01
5   17375809595660200000.000000000000000000  [2023-01-01]  2023-01-01
6   17602861391509800000.000000000000000000  [2023-01-01]  2023-01-01
7   17996457346796300000.000000000000000000  [2023-01-01]  2023-01-01
8    8233118994471985000.000000000000000000  [2023-01-01]  2023-01-01
9   16899212529494500000.000000000000000000  [2023-01-01]  2023-01-01
10   5641679155878286000.000000000000000000  [2023-01-01]  2023-01-01
11  14156386081429200000.000000000000000000  [2023-01-01]  2023-01-01
12  10060569187331700000.000000000000000000  [2023-01-01]  2023-01-01
13  14839625512044600000.000000000000000000  [2023-01-01]  2023-01-01
14  12718856434460700000.000000000000000000  [2023-01-01]  2023-01-01
15  13547985275289400000.000000000000000000  [2023-01-01]  2023-01-01
16   5289391436834807000.000000000000000000  [2023-01-01]  2023-01-01
17  12615598167083900000.000000000000000000  [2023-01-01]  2023-01-01
18  15333162782644000000.000000000000000000  [2023-01-01]  2023-01-01
19  10945278839921100000.000000000000000000  [2023-01-01]  2023-01-01
20  13650860389726700000.000000000000000000  [2023-01-01]  2023-01-01
21  13896941559230700000.000000000000000000  [2023-01-01]  2023-01-01
22   7675916199662313000.000000000000000000  [2023-01-01]  2023-01-01
23   3088852736926711000.000000000000000000  [2023-01-01]  2023-01-01
24  11355648956477300000.000000000000000000  [2023-01-01]  2023-01-01
25   7367315548640865000.000000000000000000  [2023-01-01]  2023-01-01
26   5173447199385430000.000000000000000000  [2023-01-01]  2023-01-01
27  13211327936935700000.000000000000000000  [2023-01-01]  2023-01-01
28  16683407122936000000.000000000000000000  [2023-01-01]  2023-01-01
29   2780254311411550000.000000000000000000  [2023-01-01]  2023-01-01
30  12391574664179900000.000000000000000000  [2023-01-01]  2023-01-01
31  12016633734290000000.000000000000000000  [2023-01-01]  2023-01-01
32   6998045839230058000.000000000000000000  [2023-01-01]  2023-01-01
33  16527802169428800000.000000000000000000  [2023-01-01]  2023-01-01
34   5804919602898318000.000000000000000000  [2023-01-01]  2023-01-01
35  14434469444350800000.000000000000000000  [2023-01-01]  2023-01-01
36    743774307695414700.000000000000000000  [2023-01-01]  2023-01-01
37   3072521795088519000.000000000000000000  [2023-01-01]  2023-01-01
38  11578392607604700000.000000000000000000  [2023-01-01]  2023-01-01
39   5585292244888521000.000000000000000000  [2023-01-01]  2023-01-01
40  12275582415763800000.000000000000000000  [2023-01-01]  2023-01-01
41   4250280751558363600.000000000000000000  [2023-01-01]  2023-01-01
42  15342341988434300000.000000000000000000  [2023-01-01]  2023-01-01
43  17358702759623100000.000000000000000000  [2023-01-01]  2023-01-01
44   5997934885596689000.000000000000000000  [2023-01-01]  2023-01-01
45   1527356772363511300.000000000000000000  [2023-01-01]  2023-01-01
46    137925124111668560.000000000000000000  [2023-01-01]  2023-01-01
47   9497159639052880000.000000000000000000  [2023-01-01]  2023-01-01
48  11946491903446900000.000000000000000000  [2023-01-01]  2023-01-01
49   4302730422097599000.000000000000000000  [2023-01-01]  2023-01-01
50   9447838445048410000.000000000000000000  [2023-01-01]  2023-01-01
51  13283877612593500000.000000000000000000  [2023-01-01]  2023-01-01
52   1432283348772335900.000000000000000000  [2023-01-01]  2023-01-01
53  12205325038818400000.000000000000000000  [2023-01-01]  2023-01-01
54     70132547320211180.000000000000000000  [2023-01-01]  2023-01-01
55  13580626093054200000.000000000000000000  [2023-01-01]  2023-01-01
56   4604886668373323000.000000000000000000  [2023-01-01]  2023-01-01
57  11547155521553000000.000000000000000000  [2023-01-01]  2023-01-01
58  11780863980750100000.000000000000000000  [2023-01-01]  2023-01-01
59  14113023018255200000.000000000000000000  [2023-01-01]  2023-01-01
60   6773662097638674000.000000000000000000  [2023-01-01]  2023-01-01
61   1531992429564514600.000000000000000000  [2023-01-01]  2023-01-01
62   2794586222856017000.000000000000000000  [2023-01-01]  2023-01-01
63  13647221004976700000.000000000000000000  [2023-01-01]  2023-01-01
64   1556238503289853700.000000000000000000  [2023-01-01]  2023-01-01
65  16546406506855300000.000000000000000000  [2023-01-01]  2023-01-01
66  12423778646288300000.000000000000000000  [2023-01-01]  2023-01-01
67    406876712821807740.000000000000000000  [2023-01-01]  2023-01-01
68   5017882618361265000.000000000000000000  [2023-01-01]  2023-01-01
69  16456047805589300000.000000000000000000  [2023-01-01]  2023-01-01
70  17155952271109500000.000000000000000000  [2023-01-01]  2023-01-01
71  11834646844374000000.000000000000000000  [2023-01-01]  2023-01-01
72  14769296553438200000.000000000000000000  [2023-01-01]  2023-01-01
73   2149685481453258000.000000000000000000  [2023-01-01]  2023-01-01
74   9577890054795240000.000000000000000000  [2023-01-01]  2023-01-01
75   4270724740755152000.000000000000000000  [2023-01-01]  2023-01-01
76  17996503045784700000.000000000000000000  [2023-01-01]  2023-01-01
77   8045844334478885000.000000000000000000  [2023-01-01]  2023-01-01
78    938061164068204400.000000000000000000  [2023-01-01]  2023-01-01
79  11539721681966600000.000000000000000000  [2023-01-01]  2023-01-01
80   9330177792449540000.000000000000000000  [2023-01-01]  2023-01-01
81   2014482598092651500.000000000000000000  [2023-01-01]  2023-01-01
82   4271173026220832000.000000000000000000  [2023-01-01]  2023-01-01
83  16309683947680000000.000000000000000000  [2023-01-01]  2023-01-01

In [37]:
events_df.pandas_api()

                                                                                         url                                                                                                                                               referrer                                  user_id                                device_id                   host                  event_time
0                                                                                          /                                                                                                                                                   None                                     None   9906756820661180000.000000000000000000    www.zachwilson.tech  2023-01-09 11:55:28.032000
1                                                                                          /                                                                                                                                                   None  16647130749494100000.000000000000000000   9906756820661180000.000000000000000000    www.zachwilson.tech  2023-01-09 20:10:27.610000
2                                                                                          /                                                                                                                                                   None                                     None  12048389584711700000.000000000000000000  admin.zachwilson.tech  2023-01-10 04:43:49.204000
3                                                                                          /                                                                                                                                                   None                                     None  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:03.497000
4                                                                                          /                                                                                                                                                   None                                     None  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:04.305000
5                                                                                          /                                                                                                                                                   None                                     None  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:44:51.848000
6                                                                                 /?author=4                                                                                                                                                   None                                     None   8300763538851936000.000000000000000000    www.zachwilson.tech  2023-01-22 10:29:17.735000
7                                                                                 /?author=5                                                                                                                                                   None   2854030062999680500.000000000000000000   8300763538851936000.000000000000000000    www.zachwilson.tech  2023-01-22 10:29:19.083000
8                                                                                          /                                                                                                                                                   None   7221550789269574000.000000000000000000    520733535420276540.000000000000000000    www.zachwilson.tech  2023-01-21 23:59:01.355000
9                                                                                /robots.txt                                                                                                                                                   None                                     None                                     None       www.eczachly.com  2023-01-22 00:04:54.058000
10                                                                                  /ads.txt                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:04:58.320000
11                                                                              /app-ads.txt                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:05:04.319000
12                                                                               /robots.txt                                                                                                                                                   None   4556649845972470300.000000000000000000  10598707916011500000.000000000000000000    www.zachwilson.tech  2023-01-22 01:22:16.428000
13                                                   /.well-known/apple-app-site-association                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:05:09.883000
14                                                                             /wp-login.php                                                                                                                                                   None   2854030062999680500.000000000000000000   8300763538851936000.000000000000000000    www.zachwilson.tech  2023-01-22 10:29:12.679000
15                                                               /apple-app-site-association                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:05:14.923000
16                                                                     /.well-known/nodeinfo                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:05:29.405000
17                                                         /.well-known/openid-configuration                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:05:34.806000
18                                                                 /.well-known/security.txt                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:05:39.362000
19                                                                                /?author=1                                                                                                                                                   None   2854030062999680500.000000000000000000   8300763538851936000.000000000000000000    www.zachwilson.tech  2023-01-22 10:29:13.283000
20                                                                                /?author=2                                                                                                                                                   None   2854030062999680500.000000000000000000   8300763538851936000.000000000000000000    www.zachwilson.tech  2023-01-22 10:29:14.598000
21                                                                                /?author=3                                                                                                                                                   None   2854030062999680500.000000000000000000   8300763538851936000.000000000000000000    www.zachwilson.tech  2023-01-22 10:29:15.986000
22                                                                             /security.txt                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:05:44.506000
23                                                                    /.well-known/trust.txt                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:05:49.615000
24                                                                                /trust.txt                                                                                                                                                   None  15027850815457000000.000000000000000000   6449567464980457000.000000000000000000       www.eczachly.com  2023-01-22 00:05:54.577000
25                                                                               /robots.txt                                                                                                                                                   None   6329384693585678000.000000000000000000  10598707916011500000.000000000000000000    www.zachwilson.tech  2023-01-22 00:21:40.827000
26                                                                                         /                                                                                                                                                   None  10829791756339300000.000000000000000000  10598707916011500000.000000000000000000    www.zachwilson.tech  2023-01-22 00:25:57.863000
27                                                                               /robots.txt                                                                                                                                                   None                                     None                                     None    www.zachwilson.tech  2023-01-03 18:47:23.059000
28                                                                                 /info.php                                                                                                                                                   None   9539271041292400000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:05.065000
29                                                                       /telescope/requests                                                                                                                                                   None   9539271041292400000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:05.059000
30                                                                /?rest_route=/wp/v2/users/                                                                                                                                                   None   9539271041292400000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:05.060000
31                                                                             /login.action                                                                                                                                                   None   4252588066706235000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:11.795000
32                                                                                    /about                                                                                                                                                   None   4252588066706235000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:11.799000
33                                                                                /.DS_Store                                                                                                                                                   None   4252588066706235000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:09.367000
34                                                                       /telescope/requests                                                                                                                                                   None   4252588066706235000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:09.375000
35                                                                                 /info.php                                                                                                                                                   None                                     None  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:05.524000
36                                                                                     /.env                                                                                                                                                   None   9722628434779050000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:05.527000
37                                                                             /login.action                                                                                                                                                   None   9539271041292400000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:07.613000
38                                                                             /login.action                                                                                                                                                   None  15699900397137600000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:08.522000
39                                                                                    /about                                                                                                                                                   None  15699900397137600000.000000000000000000  12048389584711700000.000000000000000000    www.zachwilson.tech  2023-01-14 05:25:08.530000
40                                                                                 /info.php                                                                                                                                                   None                                     None  12048389584711700000.000000000000000000       www.eczachly.com  2023-01-14 05:46:31.187000
41                                                                /?rest_route=/wp/v2/users/                                                                                                                                                   None                                     None  12048389584711700000.000000000000000000       www.eczachly.com  2023-01-14 05:46:31.416000
42                                                          /debug/default/view?panel=config                                                                                                                                                   None  18154154256288500000.000000000000000000  12048389584711700000.000000000000000000       www.eczachly.com  2023-01-14 05:46:31.434000
43                                                                             /login.action                                                                                                                                                   None                                     None  12048389584711700000.000000000000000000       www.eczachly.com  2023-01-14 05:46:31.738000
44                                                                             /login.action                                                                                                                                                   None  18154154256288500000.000000000000000000  12048389584711700000.000000000000000000       www.eczachly.com  2023-01-14 05:46:34.715000
45                                                                                         /                                                                                                                                                   None  14061187501322500000.000000000000000000   8453901392618209000.000000000000000000    www.zachwilson.tech  2023-01-25 23:58:59.554000
46                                                                               /robots.txt                                                                                                                                                   None                                     None                                     None    www.zachwilson.tech  2023-01-26 12:23:37.925000
47                                                                                         /                                                                                                                                                   None   6281530077625447000.000000000000000000  17786202031985000000.000000000000000000    www.zachwilson.tech  2023-01-26 12:23:38.557000
48                                                                                         /                                                                                                                                                   None   6281530077625447000.000000000000000000  17786202031985000000.000000000000000000    www.zachwilson.tech  2023-01-26 12:23:40.108000
49                                                                               /robots.txt                                                                                                                                                   None   6281530077625447000.000000000000000000  17786202031985000000.000000000000000000    www.zachwilson.tech  2023-01-26 12:23:42.013000
50                                                                               /robots.txt                                                                                                                                                   None   6281530077625447000.000000000000000000  17786202031985000000.000000000000000000    www.zachwilson.tech  2023-01-26 12:23:43.004000
51                                                                                         /                                                                                                                                                   None   6281530077625447000.000000000000000000  17786202031985000000.000000000000000000    www.zachwilson.tech  2023-01-26 12:23:43.854000

In [ ]:
user_cumulated_query = """
WITH yesterday AS (
    SELECT
        *
    FROM homework.users_cumulated
    WHERE date = to_date('2022-12-31')
),
    today AS (
            SELECT
                  CAST(user_id AS STRING),
                  CAST(event_time AS DATE) as date_active
              FROM events
              WHERE
                  CAST(event_time AS DATE) = to_date('2023-01-01')
                    AND user_id IS NOT NULL
              GROUP BY user_id, CAST(event_time AS DATE)
    )
SELECT
    COALESCE(t.user_id, y.user_id) as user_id,
    CASE WHEN y.dates_active IS NULL
            THEN array(t.date_active)
        WHEN t.date_active IS NULL
            THEN y.dates_active
        ELSE concat(array(t.date_active), y.dates_active)
        END as dates_active,
    COALESCE(t.date_active, date_add(y.date, 1)) AS date
    FROM today t
    FULL OUTER JOIN yesterday y
    ON t.user_id = y.user_id
"""